image:
  file: .gitpod.Dockerfile

tasks:
  - name: RDP
    command: echo todo # ./ngrok tcp --region $CRP 3388 &>/dev/null & echo RDP Address: && curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'